version: "3.8"
services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.29
    ports:
      - "3333:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bsuir_library
      MYSQL_USER: library
      MYSQL_PASSWORD: library
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./volumes/mysql/data:/var/lib/mysql"
      - "./Source/Server/Database:/docker-entrypoint-initdb.d"
  api:
    image: lackym/bsuir-cw-library:latest
    ports:
      - "7788:7788"
    volumes:
      - "./volumes/api/configs:/api-server-bin/configs"
      - "./volumes/api/storage:/api-server-bin/storage"
    depends_on:
      - mysql